import { addTemplate } from '@nuxt/kit';

import { version } from '../../package.json';
import { ICONS } from '../state';
import { indent } from '../runtime/utils/str';
import { templatePublicPath } from '../path';

export function createIconsTemplate()
{
    addTemplate({
        filename: templatePublicPath('icons.svg'),
        write: true,
        getContents: () => `
<!--
    Generated by Nuxt module "My Icons" v${version} at ${new Date().toISOString()}
    https://github.com/Gwynerva/nuxt-my-icons

    by Gwynerva
    https://github.com/Gwynerva

    Have fun!
-->
<svg xmlns="http://www.w3.org/2000/svg">
${indent(ICONS.symbols)}
</svg>
        `.trim(),
    });
}